version: '3'
services:
  neo4j:
    container_name: neo4j-sample
    image: neo4j:3.3.2
    environment:
      - NEO4J_AUTH=neo4j/neo
    tmpfs:
      - /data
      - /logs
    ports:
      - "7475:7474"
      - "7688:7687"
